default-resources:
  disk: 4
  mem_mb: 16000
  runtime: 86400  # 24 hours in seconds (Snakemake expects seconds)
# old:
#   --cpus-per-task={resources.threads}
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --mem={resources.mem_mb}M
    --time={resources.runtime}
    --account=hsiehph
    --partition=sioux,agsmall,aglarge
    --nodes=1
    --ntasks-per-node=1
    --cpus-per-task={threads}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}_{wildcards}.%j.out
    --export=all
    --parsable # Required to pass job IDs to scancel
jobs: 100
rerun-incomplete: True
cluster-cancel: scancel
cluster-cancel-nargs: 500 # cancel 500 jobs at a time, all will still be canceled
printshellcmds: True
reason: True
show-failed-logs: True 
latency-wait: 60
cluster-status: status-sacct.sh
use-conda: True
max-jobs-per-second: 200
#rerun-triggers: mtime 
#restart-times: 1
